# blocklist
branches:
  except:
  - scorep_headers

language: generic
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
            - cmake-data
            - libunwind8
            - libunwind8-dev
            - scorep
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - sourceline: "ppa:andreasgocht/scorep"
    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - cmake
            - cmake-data
            - libunwind8
            - libunwind8-dev
            - scorep
          sources: *sources
            - sourceline: "ppa:andreasgocht/scorep"


before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
