# blocklist
branches:
  except:
  - scorep_headers

language: generic

sudo: required

dist: bionic

matrix:
  include:
    - os: linux
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
              - sourceline: "ppa:andreasgocht/scorep"
          packages:
            - scorep       
            - g++-5
            - cmake
            - cmake-data
            - libunwind8
            - libunwind8-dev
#          sources:
#            - llvm-toolchain-precise-3.8
#            - ubuntu-toolchain-r-test
#            - george-edison55-precise-backports
    - os: linux
      env: CXX=clang++-7 CC=clang-7
      addons:
        apt:
          sources:
              - sourceline: "ppa:andreasgocht/scorep"
          packages:
            - scorep
            - clang-7
            - cmake
            - cmake-data
            - libunwind8
            - libunwind8-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
